
import {HIERARCHY_ATTRIBUTE, 
    SIZE_ATTRIBUTE, 
    THEME_ATTRIBUTE,
    STATE_ATTRIBUTE,
    ICON_ATTRIBUTE,
    WIDTH_ATTRIBUTE} from "../constants.js"
import {DESTRUCTIVE_OPTION,
    LARGE_OPTION,
    MEDIUM_OPTION,
    SMALL_OPTION,
    DARK_OPTION,
    LIGHT_OPTION,
    ACTIVE_OPTION,
    INACTIVE_OPTION,
    ON_OPTION,
    OFF_OPTION,
    FULL_OPTION,
    FIT_CONTENT_OPTION} from "../constants.js"
import {BUTTON_SUBCOMPONENT,
    ICON_SUBCOMPONENT,
    ICON_CONTAINER_SUBCOMPONENT,
    TEXT_SUBCOMPONENT } from "../constants.js"
import { DELETE_BUTTON_LIGHT_INACTIVE,
     DELETE_BUTTON_DARK_INACTIVE,
     DELETE_BUTTON_DARK_ACTIVE,
     DELETE_BUTTON_LIGHT_ACTIVE,
     DELETE_BUTTON_DARK_HOVER,
     DELETE_BUTTON_LIGHT_HOVER,
     TYPOGRAPHY_03, ICON_01, TYPOGRAPHY_01, VALIDATED_COLOR
     } from "../../commonMethodsAndConstants/Styles/commonConstants.js"
import {HOVER_BUTTON_EVENT, FOCUS_BUTTON_EVENT} from "../constants.js"
import {REGULAR_BUTTON_ICON_VARIANT, REGULAR_BUTTON_VARIANT} from "../constants.js"
import { SIZE_STYLES } from "./commonStyles.js"
import {PATH_STYLE,STYLE_OBJECT,COMPONENT_VARIANT_KEY} from "../../commonMethodsAndConstants/Styles/commonConstants.js"
const destructiveStyles = []
//*----------------STYLING BUTTONS ------------------------*/

//*----------------NEW BUTTON ------------------------*/

//* DESTRUCTIVE DESKTOP LIGHT MODE NORMAL OFFICON */
const Style1 = {}
Style1 [BUTTON_SUBCOMPONENT] = {
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT]
}
Style1[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
    background: DELETE_BUTTON_LIGHT_HOVER,
    }
Style1[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

Style1 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}
const Style1Path = {}
Style1Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style1Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style1Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style1Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style1Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style1Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper1 = {}
styleWrapper1[STYLE_OBJECT] = {...Style1}
styleWrapper1[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper1[PATH_STYLE] = Style1Path
destructiveStyles.push(styleWrapper1)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP LIGHT MODE NORMAL ONICON */

const Style2 = {}

Style2 [BUTTON_SUBCOMPONENT] = {
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT]
}
Style2[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
    background: DELETE_BUTTON_LIGHT_HOVER,
}
Style2[TEXT_SUBCOMPONENT] = {
position: "static",
color: TYPOGRAPHY_03,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}
Style2[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: TYPOGRAPHY_03,
}
Style2[ICON_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
width: "20px",
height: "20px",
}

Style2 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}

const Style2Path = {}
Style2Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style2Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style2Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style2Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style2Path[ICON_ATTRIBUTE] = ON_OPTION
Style2Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION  

const styleWrapper2 = {}
styleWrapper2[STYLE_OBJECT] = {...Style2}
styleWrapper2[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper2[PATH_STYLE] = Style2Path
destructiveStyles.push(styleWrapper2)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP LIGHT DISABLED OFFICON *//
const Style3 = {}
Style3 [BUTTON_SUBCOMPONENT] = {
background: DELETE_BUTTON_LIGHT_INACTIVE,

...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",
}
Style3[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}
const Style3Path = {}
Style3Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style3Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style3Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style3Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style3Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style3Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper3 = {}
styleWrapper3[STYLE_OBJECT] = {...Style3}
styleWrapper3[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper3[PATH_STYLE] = Style3Path
destructiveStyles.push(styleWrapper3)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP LIGHT BLACK LIGHTDISABLED ONICON *//
const Style4 = {}

Style4 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_INACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default", 
}
Style4[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}
Style4[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: TYPOGRAPHY_03,
}
Style4[ICON_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
width: "20px",
height: "20px",
}
const Style4Path = {}
Style4Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style4Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style4Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style4Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style4Path[ICON_ATTRIBUTE] = ON_OPTION 
Style4Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper4 = {}
styleWrapper4[STYLE_OBJECT] = {...Style4}
styleWrapper4[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper4[PATH_STYLE] = Style4Path
destructiveStyles.push(styleWrapper4)

//*---------TABLET AND MOBILE *-----------------------//
//*----------------NEW BUTTON ------------------------*/



//* DESTRUCTIVE TABLET&MOBILE LIGHT BLACK LIGHTNORMAL OFFICON */
const Style7 = {}
Style7 [BUTTON_SUBCOMPONENT] = {
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
padding: "11px 16px 13px 16px"

}
Style7[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_LIGHT_HOVER,
}
Style7[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

Style7 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}

const Style7Path = {}
Style7Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style7Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style7Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style7Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style7Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style7Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper7 = {}
styleWrapper7[STYLE_OBJECT] = {...Style7}
styleWrapper7[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper7[PATH_STYLE] = Style7Path
destructiveStyles.push(styleWrapper7)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE TABLET&MOBILE LIGHT BLACK LIGHTNORMAL ONICON *//
const Style8 = {}
/* Auto layout */

Style8 [BUTTON_SUBCOMPONENT] = {    
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
padding: "10px 16px 10px"

}

Style8 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}


Style8[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_LIGHT_HOVER,
}
Style8[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 

}
Style8[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: TYPOGRAPHY_03,
}
Style8[ICON_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
width: "20px",
height: "20px",
}
const Style8Path = {}
Style8Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style8Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style8Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style8Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style8Path[ICON_ATTRIBUTE] = ON_OPTION 
Style8Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper8 = {}
styleWrapper8[STYLE_OBJECT] = {...Style8}
styleWrapper8[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper8[PATH_STYLE] = Style8Path
destructiveStyles.push(styleWrapper8)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE TABLET&MOBILE BLACK LIGHT DISABLED OFFICON *//
const Style9 = {}


Style9 [BUTTON_SUBCOMPONENT] = {
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_INACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",
padding: "11px 16px 13px 16px"

}

Style9[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

const Style9Path = {}
Style9Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style9Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style9Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style9Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style9Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style9Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper9 = {}
styleWrapper9[STYLE_OBJECT] = {...Style9}
styleWrapper9[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper9[PATH_STYLE] = Style9Path
destructiveStyles.push(styleWrapper9)
//* DESTRUCTIVE TABLET&MOBILE BLACK LIGHT DISABLED OFFICON *//
const Style10 = {}


Style10 [BUTTON_SUBCOMPONENT] = {


transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_INACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",
padding: "10px 16px 10px"


}
Style10[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}

Style10[ICON_CONTAINER_SUBCOMPONENT] ={
    ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
    color: TYPOGRAPHY_03,
    }
 Style10[ICON_SUBCOMPONENT] = {
    color: TYPOGRAPHY_03,
    width: "20px",
    height: "20px",
    }

const Style10Path = {}
Style10Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style10Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style10Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style10Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style10Path[ICON_ATTRIBUTE] = ON_OPTION 
Style10Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper10 = {}
styleWrapper10[STYLE_OBJECT] = {...Style10}
styleWrapper10[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper10[PATH_STYLE] = Style10Path
destructiveStyles.push(styleWrapper10)
//*---------SMALL-----------------------//
//*----------------NEW BUTTON ------------------------*/

//* DESTRUCTIVE TABLET&MOBILE BLACK LIGHTNORMAL OFFICON */
const Style13 = {}
Style13 [BUTTON_SUBCOMPONENT] = {
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT]
}

Style13 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}

Style13[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_LIGHT_HOVER,
}
Style13[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}
const Style13Path = {}
Style13Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style13Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style13Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style13Path [STATE_ATTRIBUTE] = ACTIVE_OPTION
Style13Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style13Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper13 = {}
styleWrapper13[STYLE_OBJECT] = {...Style13}
styleWrapper13[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper13[PATH_STYLE] = Style13Path
destructiveStyles.push(styleWrapper13)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE SMALL BLACK LIGHTNORMAL ONICON *//
const Style14 = {}
/* Auto layout */

Style14 [BUTTON_SUBCOMPONENT] = {    
transition: "0.2s all ease-in-out",
position: "relative",
background: DELETE_BUTTON_LIGHT_ACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT] 
}
Style14[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_LIGHT_HOVER,
}

Style14 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_LIGHT_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}


Style14[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style14[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: TYPOGRAPHY_03,
}
Style14[ICON_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
width: "20px",
height: "20px",
}

const Style14Path = {}
Style14Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style14Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style14Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style14Path [STATE_ATTRIBUTE] = ACTIVE_OPTION
Style14Path[ICON_ATTRIBUTE] = ON_OPTION 
Style14Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper14 = {}
styleWrapper14[STYLE_OBJECT] = {...Style14}
styleWrapper14[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper14[PATH_STYLE] = Style14Path
destructiveStyles.push(styleWrapper14)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE SMALL BLACK LIGHT DISABLED OFFICON *//
const Style15 = {}


Style15 [BUTTON_SUBCOMPONENT] = {


transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_LIGHT_INACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",

}
Style15[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

const Style15Path = {}
Style15Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style15Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style15Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style15Path [STATE_ATTRIBUTE] = INACTIVE_OPTION
Style15Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style15Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper15 = {}
styleWrapper15[STYLE_OBJECT] = {...Style15}
styleWrapper15[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper15[PATH_STYLE] = Style15Path
destructiveStyles.push(styleWrapper15)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP BLACK LIGHTDISABLED ONICON *//
const Style16 = {}

Style16 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
position: "relative",
background: DELETE_BUTTON_LIGHT_INACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default", 

}
Style16[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}
Style16[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: TYPOGRAPHY_03,
}
Style16[ICON_SUBCOMPONENT] = {
color: TYPOGRAPHY_03,
width: "20px",
height: "20px",
}

const Style16Path = {}
Style16Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style16Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style16Path[THEME_ATTRIBUTE] = LIGHT_OPTION
Style16Path [STATE_ATTRIBUTE] = INACTIVE_OPTION
Style16Path[ICON_ATTRIBUTE] = ON_OPTION 
Style16Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper16 = {}
styleWrapper16[STYLE_OBJECT] = {...Style16}
styleWrapper16[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper16[PATH_STYLE] = Style16Path
destructiveStyles.push(styleWrapper16)

//*----------------NEW BUTTON ------------------------*/

//* DESTRUCTIVE DESKTOP DARK NORMAL OFFICON */

const Style19 = {}
Style19 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_ACTIVE,
cursor: "pointer",
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT]

}
Style19[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}
Style19[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

Style19 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}

const Style19Path = {}
Style19Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style19Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style19Path[THEME_ATTRIBUTE] = DARK_OPTION
Style19Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style19Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style19Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper19 = {}
styleWrapper19[STYLE_OBJECT] = {...Style19}
styleWrapper19[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper19[PATH_STYLE] = Style19Path
destructiveStyles.push(styleWrapper19)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP DARK NORMAL ONICON *//
const Style20 = {}

Style20 [BUTTON_SUBCOMPONENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_ACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT] 

}
Style20[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}

Style20 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}

Style20[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style20[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style20[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}

const Style20Path = {}
Style20Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style20Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style20Path[THEME_ATTRIBUTE] = DARK_OPTION
Style20Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style20Path[ICON_ATTRIBUTE] = ON_OPTION 
Style20Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper20 = {}
styleWrapper20[STYLE_OBJECT] = {...Style20}
styleWrapper20[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper20[PATH_STYLE] = Style20Path
destructiveStyles.push(styleWrapper20)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP DARK DISABLED OFFICON *//
const Style21 = {}

Style21 [BUTTON_SUBCOMPONENT] = {
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",

}
Style21[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

const Style21Path = {}
Style21Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style21Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style21Path[THEME_ATTRIBUTE] = DARK_OPTION
Style21Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style21Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style21Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper21 = {}
styleWrapper21[STYLE_OBJECT] = {...Style21}
styleWrapper21[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper21[PATH_STYLE] = Style21Path
destructiveStyles.push(styleWrapper21)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP DARK DISABLED ONICON *//
const Style22 = {}

Style22 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default", 

}
Style22[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style22[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style22[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}
const Style22Path = {}
Style22Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style22Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style22Path[THEME_ATTRIBUTE] = DARK_OPTION
Style22Path [STATE_ATTRIBUTE] = INACTIVE_OPTION
Style22Path[ICON_ATTRIBUTE] = ON_OPTION 
Style22Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper22 = {}
styleWrapper22[STYLE_OBJECT] = {...Style22}
styleWrapper22[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper22[PATH_STYLE] = Style22Path
destructiveStyles.push(styleWrapper22)

//*---------TABLET AND MOBILE *-----------------------//
//*----------------NEW BUTTON ------------------------*/

//* DESTRUCTIVE TABLET&MOBILE DARK NORMAL OFFICON */
const Style25 = {}
Style25 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_ACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
padding: "11px 16px 13px 16px"

}
Style25[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}

Style25 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}
Style25[TEXT_SUBCOMPONENT] = {
position: "static",
color: TYPOGRAPHY_01,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}
const Style25Path = {}
Style25Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style25Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style25Path[THEME_ATTRIBUTE] = DARK_OPTION
Style25Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style25Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style25Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper25 = {}
styleWrapper25[STYLE_OBJECT] = {...Style25}
styleWrapper25[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper25[PATH_STYLE] = Style25Path
destructiveStyles.push(styleWrapper25)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE TABLET&MOBILE DARK NORMAL ONICON *//
const Style26 = {}
/* Auto layout */

Style26 [BUTTON_SUBCOMPONENT] = {    
transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_ACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT] 

}
Style26[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}

Style26 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
    padding: "10px 16px"

}

Style26[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 

}

Style26[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style26[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}
const Style26Path = {}
Style26Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style26Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style26Path[THEME_ATTRIBUTE] = DARK_OPTION
Style26Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style26Path[ICON_ATTRIBUTE] = ON_OPTION 
Style26Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper26 = {}
styleWrapper26[STYLE_OBJECT] = {...Style26}
styleWrapper26[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper26[PATH_STYLE] = Style26Path
destructiveStyles.push(styleWrapper26)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE TABLET&MOBILE DARK DISABLED OFFICON *//
const Style27 = {}


Style27 [BUTTON_SUBCOMPONENT] = {


transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",
padding: "11px 16px 13px 16px"


}
Style27[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

const Style27Path = {}
Style27Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style27Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style27Path[THEME_ATTRIBUTE] = DARK_OPTION
Style27Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style27Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style27Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper27 = {}
styleWrapper27[STYLE_OBJECT] = {...Style27}
styleWrapper27[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper27[PATH_STYLE] = Style27Path
destructiveStyles.push(styleWrapper27)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE TABLET&MOBILE DARK DISABLED ONICON //
const Style28 = {}

Style28 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default", 
padding: "10px 16px"

}
Style28[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style28[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style28[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}
const Style28Path = {}
Style28Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style28Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style28Path[THEME_ATTRIBUTE] = DARK_OPTION
Style28Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style28Path[ICON_ATTRIBUTE] = ON_OPTION 
Style28Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper28 = {}
styleWrapper28[STYLE_OBJECT] = {...Style28}
styleWrapper28[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper28[PATH_STYLE] = Style28Path
destructiveStyles.push(styleWrapper28)

//*---------SMALL-----------------------//
//*----------------NEW BUTTON ------------------------*/

//* DESTRUCTIVE SMALL DARK NORMAL OFFICON */
const Style31 = {}
Style31 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_ACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT]

}
Style31[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}
Style31 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}
Style31[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}
const Style31Path = {}
Style31Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style31Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style31Path[THEME_ATTRIBUTE] = DARK_OPTION
Style31Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style31Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style31Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper31 = {}
styleWrapper31[STYLE_OBJECT] = {...Style31}
styleWrapper31[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper31[PATH_STYLE] = Style31Path
destructiveStyles.push(styleWrapper31)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE SMALL DARK NORMAL ONICON *//
const Style32 = {}
/* Auto layout */

Style32 [BUTTON_SUBCOMPONENT] = {    

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_ACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT] 

}

Style32 [BUTTON_SUBCOMPONENT][FOCUS_BUTTON_EVENT] = {
    transition: "0.2s all ease-in-out",
    background: DELETE_BUTTON_DARK_HOVER,
    boxShadow: `0 0 0 4px ${VALIDATED_COLOR}`,
}
Style32[BUTTON_SUBCOMPONENT][HOVER_BUTTON_EVENT] = {
background: DELETE_BUTTON_DARK_HOVER,
}
Style32[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}
Style32[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style32[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}
const Style32Path = {}
Style32Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style32Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style32Path[THEME_ATTRIBUTE] = DARK_OPTION
Style32Path[STATE_ATTRIBUTE] = ACTIVE_OPTION
Style32Path[ICON_ATTRIBUTE] = ON_OPTION 
Style32Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper32 = {}
styleWrapper32[STYLE_OBJECT] = {...Style32}
styleWrapper32[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper32[PATH_STYLE] = Style32Path
destructiveStyles.push(styleWrapper32)

//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE SMALL DARK DISABLED OFFICON *//
const Style33 = {}


Style33 [BUTTON_SUBCOMPONENT] = {


transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default",

}
Style33[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_VARIANT][TEXT_SUBCOMPONENT]
}

const Style33Path = {}
Style33Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style33Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style33Path[THEME_ATTRIBUTE] = DARK_OPTION
Style33Path [STATE_ATTRIBUTE] = INACTIVE_OPTION
Style33Path[ICON_ATTRIBUTE] = OFF_OPTION 
Style33Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper33 = {}
styleWrapper33[STYLE_OBJECT] = {...Style33}
styleWrapper33[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_VARIANT
styleWrapper33[PATH_STYLE] = Style33Path
destructiveStyles.push(styleWrapper33)
//*----------------NEW BUTTON ------------------------*/
//* DESTRUCTIVE DESKTOP DARK DISABLED ONICON *//
const Style34 = {}

Style34 [BUTTON_SUBCOMPONENT] = {

transition: "0.2s all ease-in-out",
background: DELETE_BUTTON_DARK_INACTIVE,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
cursor: "default", 

}
Style34[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style34[ICON_CONTAINER_SUBCOMPONENT] ={
...SIZE_STYLES[SMALL_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
color: ICON_01,
}
Style34[ICON_SUBCOMPONENT] = {
color: ICON_01,
width: "20px",
height: "20px",
}
const Style34Path = {}
Style34Path[HIERARCHY_ATTRIBUTE] = DESTRUCTIVE_OPTION
Style34Path[SIZE_ATTRIBUTE] = SMALL_OPTION
Style34Path[THEME_ATTRIBUTE] = DARK_OPTION
Style34Path[STATE_ATTRIBUTE] = INACTIVE_OPTION
Style34Path[ICON_ATTRIBUTE] = ON_OPTION 
Style34Path[WIDTH_ATTRIBUTE] = FIT_CONTENT_OPTION 

const styleWrapper34 = {}
styleWrapper34[STYLE_OBJECT] = {...Style34}
styleWrapper34[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper34[PATH_STYLE] = Style34Path
destructiveStyles.push(styleWrapper34)


const copyDestructiveStyles = []
destructiveStyles.forEach((style,index) => {
    copyDestructiveStyles.push(JSON.parse(JSON.stringify(style)))
    copyDestructiveStyles[index][STYLE_OBJECT][BUTTON_SUBCOMPONENT].width = "100%"
    copyDestructiveStyles[index][PATH_STYLE][WIDTH_ATTRIBUTE] = FULL_OPTION
})
destructiveStyles.push(...copyDestructiveStyles)

export {destructiveStyles}