import { SIZE_FUNCTION_PARSING } from "../constants.js"
import { XL_OPTION, L_OPTION, M_OPTION, S_OPTION } from "../constants.js"
const GRID = {nCol:{}, space:{},margin:{}}
GRID.nCol[XL_OPTION] = 12
GRID.space[XL_OPTION] = 32
GRID.margin[XL_OPTION] = 32

GRID.nCol[L_OPTION] = 12
GRID.space[L_OPTION] = 32
GRID.margin[L_OPTION] = 32

GRID.nCol[M_OPTION] = 6
GRID.space[M_OPTION] = 32
GRID.margin[M_OPTION] = 32

GRID.nCol[S_OPTION] = 2
GRID.space[S_OPTION] = 16
GRID.margin[S_OPTION] = 16

const LAYOUT_MODAL = {nCol:{}, nSpace:{}}
LAYOUT_MODAL.nCol[XL_OPTION] = 6
LAYOUT_MODAL.nSpace[XL_OPTION] = 8
LAYOUT_MODAL.nCol[L_OPTION] = 8
LAYOUT_MODAL.nSpace[L_OPTION] = 10
LAYOUT_MODAL.nCol[M_OPTION] = 4
LAYOUT_MODAL.nSpace[M_OPTION] = 6
LAYOUT_MODAL.nCol[S_OPTION] = 2
LAYOUT_MODAL.nSpace[S_OPTION] = 1

const LAYOUT_MODAL_FULLSCREEN = JSON.parse(JSON.stringify(LAYOUT_MODAL))
LAYOUT_MODAL_FULLSCREEN.nSpace[XL_OPTION] = 5
LAYOUT_MODAL_FULLSCREEN.nSpace[L_OPTION] = 7
LAYOUT_MODAL_FULLSCREEN.nSpace[M_OPTION] = 3


const PADDING_MODAL = {}
PADDING_MODAL[XL_OPTION] = "48px"
PADDING_MODAL[L_OPTION] = "48px"
PADDING_MODAL[M_OPTION] = "48px"
PADDING_MODAL[S_OPTION] = "24px 8px"

const POSITION_ICON_CLOSE = {top:{}, right:{},width:{},height:{}}
POSITION_ICON_CLOSE.top[XL_OPTION] = "24px"
POSITION_ICON_CLOSE.right[XL_OPTION] = "24px"
POSITION_ICON_CLOSE.width[XL_OPTION] = "32px"
POSITION_ICON_CLOSE.height[XL_OPTION] = "32px"

POSITION_ICON_CLOSE.top[L_OPTION] = "24px"
POSITION_ICON_CLOSE.right[L_OPTION] = "24px"
POSITION_ICON_CLOSE.width[L_OPTION] = "32px"
POSITION_ICON_CLOSE.height[L_OPTION] = "32px"

POSITION_ICON_CLOSE.top[M_OPTION] = "24px"
POSITION_ICON_CLOSE.right[M_OPTION] = "24px"
POSITION_ICON_CLOSE.width[M_OPTION] = "32px"
POSITION_ICON_CLOSE.height[M_OPTION] = "32px"

POSITION_ICON_CLOSE.top[S_OPTION] = "24px"
POSITION_ICON_CLOSE.right[S_OPTION] = "8px"
POSITION_ICON_CLOSE.width[S_OPTION] = "24px"
POSITION_ICON_CLOSE.height[S_OPTION] = "24px"

const POSITION_ICON_CLOSE_FULLSCREEN = {top:{}, right:{},width:{},height:{}}
POSITION_ICON_CLOSE_FULLSCREEN.top[XL_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.right[XL_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.width[XL_OPTION] = "40px"
POSITION_ICON_CLOSE_FULLSCREEN.height[XL_OPTION] = "40px"

POSITION_ICON_CLOSE_FULLSCREEN.top[L_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.right[L_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.width[L_OPTION] = "40px"
POSITION_ICON_CLOSE_FULLSCREEN.height[L_OPTION] = "40px"

POSITION_ICON_CLOSE_FULLSCREEN.top[M_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.right[M_OPTION] = "32px"
POSITION_ICON_CLOSE_FULLSCREEN.width[M_OPTION] = "40px"
POSITION_ICON_CLOSE_FULLSCREEN.height[M_OPTION] = "40px"

POSITION_ICON_CLOSE_FULLSCREEN.top[S_OPTION] = "24px"
POSITION_ICON_CLOSE_FULLSCREEN.right[S_OPTION] = "16px"
POSITION_ICON_CLOSE_FULLSCREEN.width[S_OPTION] = "24px"
POSITION_ICON_CLOSE_FULLSCREEN.height[S_OPTION] = "24px"

export {PADDING_MODAL}
export {POSITION_ICON_CLOSE}
export {POSITION_ICON_CLOSE_FULLSCREEN}
export {GRID}
export {LAYOUT_MODAL}
export {LAYOUT_MODAL_FULLSCREEN}
export const widthOneColumn = function () {
    const vw = Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0)
    const value = SIZE_FUNCTION_PARSING()
    const widthOneColumn = (vw - 2 * GRID.margin[value] - (GRID.nCol[value] - 1) * (GRID.space[value])) / GRID.nCol[value]  
    return widthOneColumn;
}   