
import {SIZE_ATTRIBUTE, 
        COLOR_ATTRIBUTE} from "../constants.js"
import {LARGE_OPTION,
        MEDIUM_OPTION,
        DARK_OPTION,
        LIGHT_OPTION} from "../constants.js"
import {BUTTON_SUBCOMPONENT,
        ICON_SUBCOMPONENT,
        ICON_CONTAINER_SUBCOMPONENT,
        TEXT_SUBCOMPONENT } from "../constants.js"
import {ICON_ID} from "../constants.js"
import {HOVER, CLICK_TOGGLE, CLICK_TOGGLE_HOVER} from "../constants.js"
import {REGULAR_BUTTON_ICON_VARIANT} from "../constants.js"
import {PATH_STYLE,
        STYLE_OBJECT,
        COMPONENT_VARIANT_KEY,
        TYPOGRAPHY_01,
        TYPOGRAPHY_03,
        DARK_GREY,
        BRAND_CLAY_2,
        PRIMARY_BUTTON_DARK_ACTIVE,
        SECONDARY_BUTTON_LIGHT_ACTIVE} from "../../commonMethodsAndConstants/Styles/commonConstants.js"
import { ICON_SELECTION_ATTRIBUTE as ICON_SELECTION_ATTRIBUTE_FOR_COMPONENT} from "../../Icons/constants.js"
import { ICON_COLOR_ATTRIBUTE, 
         ICON_HEIGHT_ATTRIBUTE,
         ICON_WIDTH_ATTRIBUTE } from "../../Icons/constants.js"
import { SIZE_STYLES } from "./commonStyles.js"
const toggleButtonStyles = []
//*----------------STYLING BUTTONS ------------------------*/

//*----------------NEW BUTTON ------------------------*/

//* PRIMARY DESKTOP BLACK NORMAL OFFICON */
const Style1 = {}
Style1 [BUTTON_SUBCOMPONENT] = {
        transition: "0.05s all ease-in-out",
        background: "transparent",
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        padding: "12px 15px 14px",
        border: `1px solid ${PRIMARY_BUTTON_DARK_ACTIVE}`,
        borderRadius: "24px",
}
Style1[BUTTON_SUBCOMPONENT][HOVER] = {
        padding: "11px 14px 13px",
        border: `2px solid ${PRIMARY_BUTTON_DARK_ACTIVE}`,
}
Style1 [BUTTON_SUBCOMPONENT][CLICK_TOGGLE] = {
        transition: "0.2s all ease-in-out",
        background: TYPOGRAPHY_01,
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        borderRadius: "24px",
}
Style1[BUTTON_SUBCOMPONENT][CLICK_TOGGLE_HOVER] = {
        background: DARK_GREY,
}
Style1[TEXT_SUBCOMPONENT] = {
color: TYPOGRAPHY_01,
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}
Style1[TEXT_SUBCOMPONENT][CLICK_TOGGLE] = {
        color: TYPOGRAPHY_03,
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}


Style1[ICON_CONTAINER_SUBCOMPONENT] ={
    ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
    color: TYPOGRAPHY_01,
}
 Style1[ICON_CONTAINER_SUBCOMPONENT][CLICK_TOGGLE] ={
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
        color: TYPOGRAPHY_03,
}
Style1[ICON_SUBCOMPONENT] = {}
Style1[ICON_SUBCOMPONENT][COLOR_ATTRIBUTE] = TYPOGRAPHY_01
Style1[ICON_SUBCOMPONENT][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style1[ICON_SUBCOMPONENT][ICON_WIDTH_ATTRIBUTE] = "20px"
Style1[ICON_SUBCOMPONENT]['id'] = ICON_ID

Style1[ICON_SUBCOMPONENT][HOVER] = {}

Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE] = {}
Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE]['id'] = ICON_ID
Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE][COLOR_ATTRIBUTE] = TYPOGRAPHY_03
Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_WIDTH_ATTRIBUTE] = "20px"

Style1[ICON_SUBCOMPONENT][CLICK_TOGGLE_HOVER] = {}
const Style1Path = {}
Style1Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style1Path[COLOR_ATTRIBUTE] = LIGHT_OPTION
const styleWrapper1 = {}
styleWrapper1[STYLE_OBJECT] = {...Style1}
styleWrapper1[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper1[PATH_STYLE] = Style1Path


toggleButtonStyles.push(styleWrapper1)
const Style2 = {}
Style2 [BUTTON_SUBCOMPONENT] = {
        transition: "0.05s all ease-in-out",
        background: "transparent",
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        padding: "6px 15px 8px",
        border: `1px solid ${PRIMARY_BUTTON_DARK_ACTIVE}`,
        borderRadius: "24px",
        
        }
Style2[BUTTON_SUBCOMPONENT][HOVER] = {
        padding: "5px 14px 7px",
        border: `2px solid ${PRIMARY_BUTTON_DARK_ACTIVE}`,
        }
Style2 [BUTTON_SUBCOMPONENT][CLICK_TOGGLE] = {

        transition: "0.2s all ease-in-out",
        background: TYPOGRAPHY_01,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        borderRadius: "24px",
        }
Style2[BUTTON_SUBCOMPONENT][CLICK_TOGGLE_HOVER] = {
            background: DARK_GREY,
        }
Style2[TEXT_SUBCOMPONENT] = {
        color: TYPOGRAPHY_01,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}
Style2[TEXT_SUBCOMPONENT][CLICK_TOGGLE] = {
        color: TYPOGRAPHY_03,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}
Style2[ICON_CONTAINER_SUBCOMPONENT] ={
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
        color: TYPOGRAPHY_01,
        }
Style2[ICON_CONTAINER_SUBCOMPONENT][CLICK_TOGGLE] ={
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
        color: TYPOGRAPHY_03,
}
Style2[ICON_SUBCOMPONENT] = {}
Style2[ICON_SUBCOMPONENT][COLOR_ATTRIBUTE] = TYPOGRAPHY_01
Style2[ICON_SUBCOMPONENT][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style2[ICON_SUBCOMPONENT][ICON_WIDTH_ATTRIBUTE] = "20px"
Style2[ICON_SUBCOMPONENT]['id'] = ICON_ID

Style2[ICON_SUBCOMPONENT][HOVER] = {}

Style2[ICON_SUBCOMPONENT][CLICK_TOGGLE] = {}
Style2[ICON_SUBCOMPONENT][CLICK_TOGGLE]['id'] = ICON_ID
Style2[ICON_SUBCOMPONENT][CLICK_TOGGLE][COLOR_ATTRIBUTE] = TYPOGRAPHY_03
Style2[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style2[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_WIDTH_ATTRIBUTE] = "20px"
const Style2Path = {}
Style2Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style2Path[COLOR_ATTRIBUTE] = LIGHT_OPTION
const styleWrapper2 = {}
styleWrapper2[STYLE_OBJECT] = {...Style2}
styleWrapper2[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper2[PATH_STYLE] = Style2Path
toggleButtonStyles.push(styleWrapper2)


const Style3 = {}
Style3 [BUTTON_SUBCOMPONENT] = {
transition: "0.05s all ease-in-out",
background: "transparent",
...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
padding: "12px 15px 14px",
border: `1px solid ${SECONDARY_BUTTON_LIGHT_ACTIVE}`,
borderRadius: "24px",

}
Style3[BUTTON_SUBCOMPONENT][HOVER] = {
padding: "11px 14px 13px",
border: `2px solid ${SECONDARY_BUTTON_LIGHT_ACTIVE}`,
}
Style3 [BUTTON_SUBCOMPONENT][CLICK_TOGGLE] = {
        transition: "0.2s all ease-in-out",
        background: BRAND_CLAY_2,
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        borderRadius: "24px",
        }
Style3[BUTTON_SUBCOMPONENT][CLICK_TOGGLE_HOVER] = {
            background: TYPOGRAPHY_03,
}
Style3[TEXT_SUBCOMPONENT] = {
        color: TYPOGRAPHY_03,
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}
Style3[TEXT_SUBCOMPONENT][CLICK_TOGGLE] = {
        color: TYPOGRAPHY_01,
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style3[ICON_CONTAINER_SUBCOMPONENT] ={
    ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
    color: TYPOGRAPHY_03,
    }
Style3[ICON_CONTAINER_SUBCOMPONENT][CLICK_TOGGLE] ={
        ...SIZE_STYLES[LARGE_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
        color: TYPOGRAPHY_01,
}
Style3[ICON_SUBCOMPONENT] = {}
Style3[ICON_SUBCOMPONENT][COLOR_ATTRIBUTE] = TYPOGRAPHY_03
Style3[ICON_SUBCOMPONENT][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style3[ICON_SUBCOMPONENT][ICON_WIDTH_ATTRIBUTE] = "20px"
Style3[ICON_SUBCOMPONENT]['id'] = ICON_ID

Style3[ICON_SUBCOMPONENT][HOVER] = {}

Style3[ICON_SUBCOMPONENT][CLICK_TOGGLE] = {}
Style3[ICON_SUBCOMPONENT][CLICK_TOGGLE]['id'] = ICON_ID
Style3[ICON_SUBCOMPONENT][CLICK_TOGGLE][COLOR_ATTRIBUTE] = TYPOGRAPHY_01
Style3[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style3[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_WIDTH_ATTRIBUTE] = "20px"

const Style3Path = {}
Style3Path[SIZE_ATTRIBUTE] = LARGE_OPTION
Style3Path[COLOR_ATTRIBUTE] = DARK_OPTION

const styleWrapper3 = {}
styleWrapper3[STYLE_OBJECT] = {...Style3}
styleWrapper3[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper3[PATH_STYLE] = Style3Path
toggleButtonStyles.push(styleWrapper3)

const Style4 = {}
Style4 [BUTTON_SUBCOMPONENT] = {
transition: "0.05s all ease-in-out",
background: "transparent",
...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
padding: "6px 15px 8px",
border: `1px solid ${SECONDARY_BUTTON_LIGHT_ACTIVE}`,
borderRadius: "24px",

}
Style4[BUTTON_SUBCOMPONENT][HOVER] = {
padding: "5px 14px 7px",
border: `2px solid ${SECONDARY_BUTTON_LIGHT_ACTIVE}`,
}
Style4 [BUTTON_SUBCOMPONENT][CLICK_TOGGLE] = {
        transition: "0.2s all ease-in-out",
        background: BRAND_CLAY_2,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][BUTTON_SUBCOMPONENT],
        borderRadius: "24px",
        }
Style4[BUTTON_SUBCOMPONENT][CLICK_TOGGLE_HOVER] = {
            background: TYPOGRAPHY_03,
}
Style4[TEXT_SUBCOMPONENT] = {
        color: TYPOGRAPHY_03,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT]
}
Style4[TEXT_SUBCOMPONENT][CLICK_TOGGLE] = {
        color: TYPOGRAPHY_01,
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][TEXT_SUBCOMPONENT] 
}

Style4[ICON_CONTAINER_SUBCOMPONENT] ={
    ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
    color: TYPOGRAPHY_03,
    }
Style4[ICON_CONTAINER_SUBCOMPONENT][CLICK_TOGGLE] ={
        ...SIZE_STYLES[MEDIUM_OPTION][REGULAR_BUTTON_ICON_VARIANT][ICON_CONTAINER_SUBCOMPONENT],
        color: TYPOGRAPHY_01,
}
Style4[ICON_SUBCOMPONENT] = {}
Style4[ICON_SUBCOMPONENT][COLOR_ATTRIBUTE] = TYPOGRAPHY_03
Style4[ICON_SUBCOMPONENT][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style4[ICON_SUBCOMPONENT][ICON_WIDTH_ATTRIBUTE] = "20px"
Style4[ICON_SUBCOMPONENT]['id'] = ICON_ID

Style4[ICON_SUBCOMPONENT][HOVER] = {}

Style4[ICON_SUBCOMPONENT][CLICK_TOGGLE] = {}
Style4[ICON_SUBCOMPONENT][CLICK_TOGGLE]['id'] = ICON_ID
Style4[ICON_SUBCOMPONENT][CLICK_TOGGLE][COLOR_ATTRIBUTE] = TYPOGRAPHY_01
Style4[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_HEIGHT_ATTRIBUTE] = "20px"
Style4[ICON_SUBCOMPONENT][CLICK_TOGGLE][ICON_WIDTH_ATTRIBUTE] = "20px"

const Style4Path = {}
Style4Path[SIZE_ATTRIBUTE] = MEDIUM_OPTION
Style4Path[COLOR_ATTRIBUTE] = DARK_OPTION

const styleWrapper4 = {}
styleWrapper4[STYLE_OBJECT] = {...Style4}
styleWrapper4[COMPONENT_VARIANT_KEY] = REGULAR_BUTTON_ICON_VARIANT
styleWrapper4[PATH_STYLE] = Style4Path
toggleButtonStyles.push(styleWrapper4)
export  {toggleButtonStyles};